export { default as CurrentArchitectureProblemsSlide } from './current-architecture-problems-slide'
export { default as ProposedSolutionSlide } from './proposed-solution-slide'
export { default as ArchitectureTitleSlide } from './architecture-title-slide'
export { default as TargetArchitectureSlide } from './target-architecture-slide'
export { default as MethodologyTitleSlide } from './methodology-title-slide'
export { default as ScrumMethodologySlide } from './scrum-methodology-slide'
